#!/bin/zsh

# To colorize output
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
RESET="\033[0m"
export GOINFRE=/Volumes/Storage/goinfre/$(whoami)

# Check if user has directory in goinfre, makes one if not
if [ ! -d "$GOINFRE" ] ; then
	echo "${RED}Directory goinfre does not exist."
	echo "${YELLOW}Creating goinfre directory."
	mkdir $GOINFRE
	if [ -d "$GOINFRE" ] ; then
		echo "${GREEN}Successfully created goinfre directory."
	fi
	else
	echo "${GREEN}goinfre directory already exists."
	fi

	# Check if Homebrew is installed, installs it if not
	if [ ! -d "$GOINFRE/brew/bin" ] ; then
	echo "${RED}Homebrew is not installed."
	echo "${YELLOW}Installing Homebrew."
	git clone https://github.com/Homebrew/homebrew.git $GOINFRE/brew
	if [ -d "$GOINFRE/brew/bin" ] ; then
		echo "${GREEN}Successfully installed Homebrew."
	fi
fi

# Check if PATH variable has been modified to use homebrew, changes it accordingly
while true ; do
	case ":$PATH:" in
	  *:$GOINFRE/brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:*) echo "${GREEN}PATH OK." ; break ;;
	  *) echo "${RED}PATH needs to be changed" ; echo "${YELLOW}Attempting to change PATH${RESET}" ;
				echo "export PATH=$GOINFRE/brew/bin:${PATH}" >> ~/.zshrc ; export PATH=$GOINFRE/brew/bin:${PATH} ;;
	esac

	# Checks that PATH was successfully changed
	case ":$PATH:" in
	  *:$GOINFRE/brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:*) echo "${GREEN}PATH Changed successfully." ;;
	  *) echo "${RED}Failed to change PATH${RESET}" ;;
	esac
	break
done

# Update Homebrew
echo "${YELLOW}Updating Homebrew.${GREEN}"
brew update
echo "${RESET}--------------------"

# Prompt to install / update packages or exit
while true ; do
	read -p "Would you like to install / update any Homebrew packages? [y/n] " yn
	case $yn in
		[Yy]* ) break ;;
		[Nn]* ) exec /bin/zsh ; exit ;;
		* ) echo "${RED}Please answer y for yes or n to exit.${RESET}"
	esac
done
################################################################################
######### DELETE BETWEEN THE * TO REMOVE PACKAGE FROM AUTO INSTALL #############
################################################################################

# **************************NODE START******************************************
# Prompt to install / update Node
if [ ! -e "$GOINFRE/brew/bin/node" ] ; then
	brew install node
	if [ -e "$GOINFRE/brew/bin/node" ] ; then
		echo "${GREEN}Node successfully installed. Version: \c" ; node --version ; echo "${RESET}"
	else
		echo "${RED}Node failed to install.${RESET}"
	fi
else
	while true ; do
		echo "Node is already installed. ${GREEN}Version:${RESET} \c" ; node --version
    read -p "Would you like to update it? [y/n] " yn
    case $yn in
        [Yy]* ) brew upgrade node ; break ;;
        [Nn]* ) break ;;
        * ) echo "${RED}Please answer y for yes or n for no.${RESET}" ;;
    esac
	done
fi
echo "--------------------"
# ****************************NODE END******************************************


# ***************************NPM START******************************************
# Prompt to update npm
while true ; do
	if [ -e "$GOINFRE/brew/bin/node" ] ; then
		if [ ! -e "$GOINFRE/brew/bin/npm" ] ; then
			read -p "${YELLOW}You have node, but npm seems to be missing. Would you like to install it?${RESET} [y/n] " yn
			case $yn in
				[Yy]* ) brew install npm ; break ;;
				[Nn]* ) break ;;
				* ) echo "${RED}Please answer y for yes or n for no.${RESET}" ;;
			esac
			if [ -e "$GOINFRE/brew/bin/npm" ] ; then
				echo "${GREEN}npm successfully installed. Version: v\c" ; npm --version ; echo "${RESET}"
			else
				echo "${RED}npm failed to install.${RESET}"
			fi
		else
			echo "npm ${GREEN}Version:${RESET} v\c" ; npm --version
			read -p "Would you like to update it? [y/n] " yn
			case $yn in
				[Yy]* ) brew upgrade npm ; break ;;
				[Nn]* ) break ;;
				* ) echo "${RED}Please answer y for yes or n for no.${RESET}"
			esac
		fi
	fi
done
echo "--------------------"
# ***************************NPM END********************************************


# *************************BOWER START******************************************
# Prompt to install / update bower
if [ ! -e "$GOINFRE/brew/bin/bower" ] ; then
	brew install bower
	if [ -e "$GOINFRE/brew/bin/bower" ] ; then
		echo "${GREEN}Bower successfully installed. Version: v\c" ; bower --version ; echo "${RESET}"
	else
		echo "${RED}Bower failed to install.${RESET}"
	fi
else
	while true ; do
		echo "Bower is already installed. ${GREEN}Version:${RESET} v\c" ; bower --version
		read -p "Would you like to update it? [y/n] " yn
		case $yn in
			[Yy]* ) brew upgrade bower ; break ;;
			[Nn]* ) break ;;
			* ) echo "${RED}Please answer y for yes or n for no.${RESET}"
		esac
	done
fi
echo "--------------------"
# ***************************BOWER END******************************************

# ------------------------------------------------------------------------------
# *********************INSERT CUSTOM PACKAGES HERE******************************
# ------------------------------------------------------------------------------

# 1 - Remove the # between the if and the echo statements and replace PACKAGE-NAME with the package you want to add (no caps).
# 2 - add another && [ -e "$GOINFRE/brew/bin/PACKAGE-NAME"] to the if statement at the bottom.

#if [ ! -e "$GOINFRE/brew/bin/PACKAGE-NAME" ] ; then
#  brew install PACKAGE-NAME
#		if [ -e "$GOINFRE/brew/bin/PACKAGE-NAME" ] ; then
#			echo "${GREEN}PACKAGE-NAME successfully installed. Version: \c" ; PACKAGE-NAME --version ; echo "${RESET}"
#		else
#			echo "${RED}PACKAGE-NAME failed to install.${RESET}"
#		fi
#else
#	echo  "\nPACKAGE-NAME is already installed. ${GREEN}Version:${RESET} \c" ; PACKAGE-NAME --version
#    while true ;  do
#      read -p "Would you like to update it? [y/n] " yn
#    	case $yn in
#        	[Yy]* ) brew upgrade PACKAGE-NAME ; break ;;
#        	[Nn]* ) break ;;
#        	* ) echo "${RED}Please answer y for yes or n for no.${RESET}" ;;
#    	esac
#    done
#	fi
#done
#echo "--------------------"

# ------------------------------------------------------------------------------
# ************************END CUSTOM PACKAGES***********************************
# ------------------------------------------------------------------------------

# Terminates script
# Add new packages in the if statement below
if [ -e "$GOINFRE/brew/bin/node" ] && [ -e "$GOINFRE/brew/bin/npm" ] && [ -e "$GOINFRE/brew/bin/bower" ] ; then
	echo "${YELLOW}*********************************************************************************************************"
	echo "${GREEN}Homebrew and all packages included in script have been installed successfully, or were already installed"
	echo "${YELLOW}*********************************************************************************************************${RESET}"
else
	echo "${RED}There was an error installing one or more packages. Scroll up and look for error messages.${RESET}"
fi
# Sources .zshrc (oh-my-zsh didn't like me sourcing it the normal way)
exec /bin/zsh
exit
